title: Agus S. Mubarok
author: Agus S. Mubarok
description: Personal Portfolio
url: https://gusrylmubarok.github.io/
timezone: Asia/Jakarta

links:
  github: https://github.com/gusrylmubarok
  linkedin: https://www.linkedin.com/in/agussyahrilmubarok
  instagram: https://www.instagram.com/gusrylmubarok
  twitter: https://twitter.com/gusrylmubarok
  email: mailto:gusrylmubarok@gmail.com
  cekongkir: https://github.com/ORBIT58/cekongkir
  jekyll: https://jekyllrb.com

collections:
  posts:
    output: true
    permalink: /news/:title

paginate: 8
paginate_path: /news/:num

sass:
  style: compressed
strict_front_matter: true

twitter:
  username: gusrylmubarok
  card: summary

plugins:
- jekyll-feed
- jekyll-gist
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
- jekyll-redirect-from

# https://jekyllrb.com/docs/configuration/default/
exclude:
- .github
- .gitignore
- .jekyll-cache
- .sass-cache
- CNAME
- LICENSE
- README.md
